{"status": "broken", "uuid": "3d95e7d4-466c-490c-99c0-bd512e15af87", "labels": [{"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "mayank-mahajan-retina.local"}, {"name": "thread", "value": "821-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test"}], "historyId": "01ef8cdb5be4dcca613f0e4b37d06249", "name": "test_1", "fullName": "test.TestApi#test_1", "statusDetails": {"message": "TypeError: __init__() takes exactly 5 arguments (3 given)", "trace": "self = <tests.test.TestApi object at 0x10f925450>\n\n    @pytest.fixture(scope=\"session\")\n    def actions(self):\n>       return Actions(base_url=self.proxy_server_base_url, test_header=self.test_header).generate_request()\nE       TypeError: __init__() takes exactly 5 arguments (3 given)\n\ntests/test.py:21: TypeError"}, "attachments": [{"source": "80301e4d-54b9-4d9e-be2d-2a2806780f7e-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "f84d13c5-5d74-402e-8ee6-5fceb4300fdd-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "c775e29c-e15c-4466-b13a-7ea9c50560a8-attachment.txt", "type": "text/plain", "name": "stderr"}]}